"""Add is_deleted to TrackedMealFood

Revision ID: 2498205b9e48
Revises: d0c142fbf0b0
Create Date: 2025-10-02 13:22:15.674346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2498205b9e48'
down_revision: Union[str, None] = 'd0c142fbf0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_meal_foods', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_meal_foods', 'is_deleted')
    # ### end Alembic commands ###
