"""add browserless api key to llm config

Revision ID: 4522e2de4143
Revises: 882af51512ff
Create Date: 2025-10-04 15:06:27.893934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4522e2de4143'
down_revision: Union[str, None] = '882af51512ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browserless_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_configs', schema=None) as batch_op:
        batch_op.drop_column('browserless_api_key')
    # ### end Alembic commands ###
